name: Format Checks

on: [push]

jobs:
  format_checks:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2020-01-13
    steps:
    - uses: actions/checkout@v1
    - name: make check_format
      run: make check_format
